### ISSUE TITLE
Multiple commands in the same PR are not recognized

### ISSUE THREAD

**Issue by lo1tuma** [ahmed-taj/dep#10]
Lets say I have the PR `#123` and I add two comments to this PR

* first comment `/depends on #121`
* second comment `/depends on #122`

then the commit status only includes the dependency of the latest comment, i.e. "Blocked by `#122`".
I would expect to have the status "Blocked by `#121` and `#122`".

**Comment by z0al** [comment]
Closing this as it's no longer valid due to #11 

Thanks!
