### ISSUE TITLE
Post a green status when there are no dependencies.

### ISSUE THREAD

**Issue by iphydf** [ahmed-taj/dep#14]
Without a green status posted on every PR, we can't make DEP a required check.

**Comment by z0al** [comment]
If I understand this right, it should be working. If it doesn't then there is probably a bug 

Or the app didn't receive the GitHub event (probably because it's currently hosted on free [Heroku](https://heroku.com) instance).

Can you please provide an example?

**Comment by iphydf** [comment]
https://github.com/TokTok/c-toxcore/pull/799 just created, no DEP check.

**Comment by z0al** [comment]
Turns out `removeLabel` raises an exception if the label isn't assigned to that PR. 

https://github.com/ahmed-taj/dep/blob/9e07839896d6a1ea4989be8f86b9afe2e8d454bd/lib/toggle.js#L23-L24

This is definitely a bug, thanks for reporting!

**Comment by z0al** [comment]
@iphydf this should be fixed now, but I can't recheck on that PR. Does the app still has access to that repository?

**Comment by iphydf** [comment]
Yes, DEP should still be installed.

**Comment by iphydf** [comment]
It's working: https://github.com/TokTok/py-toxcore-c/pull/24

I've made DEP a required check now. Thanks.

**Comment by z0al** [comment]
You're welcome
