### ISSUE TITLE
DEP status lost on new commit

### ISSUE THREAD

**Issue by zetaron** [ahmed-taj/dep#20]
I've discovered that DEP currently doesn't act on PRs receiving new commits, which leads to the status being not reported on the most current commit (the one used by github to compute the overall status). That's unfortunate as it prevents me from adding it to the list of required status.

It would be awesome to add DEP to the list of required PR status so that no one can accidentally merge a PR that is awaiting dependencies (eg. because it's based on an other PRs Branch).

**Comment by z0al** [comment]
Thanks @zetaron for reporting this 👍

I will check the logs and try to figure out what is going on. May you please provide some context? e.g. a PR link?

**Comment by z0al** [comment]
Oh, just letting you know that this would take a day or so since my laptop isn't working right now hehe

**Comment by zetaron** [comment]
@ahmed-taj No preassure! Just wanted to bring it to your attention as it seemed odd to me at first :)

If you want I could try to come up with a PR.

**Comment by zetaron** [comment]
Also I can try to setup a test repository to showcase the issue.

**Comment by z0al** [comment]
Great! Be my guest ;)

Also, we may need to consider that app might get rate limited since it's hosted on an OSS Zeit plan (https://now.sh) !

**Comment by zetaron** [comment]
@ahmed-taj good to know, so maybe it's wise to host a small personal version... maybe add a hint to the readme and/or the github installation page?

**Comment by z0al** [comment]
You're right, I will add this to the installation page shortly!

**Comment by z0al** [comment]
Hey @zetaron. I've updated the [installation page](https://github.com/apps/dep) and will do the same on the README soon. 

> Also I can try to setup a test repository to showcase the issue.

Do you have more info you would like to share?

**Comment by zetaron** [comment]
@ahmed-taj No I've nothing to add, as soon as the repository is set up I can try to help reproduce this issue for further investigation.

As the repository I originally discovered it is a private one I can't share much more :s sorry.

Thanks for caring so much!

**Comment by nesl247** [comment]
I think this just needs:

```
robot.on('pull_request.synchronize', update)
```

here: https://github.com/z0al/dep/blob/999cc9bf74059404321d8323403c7ffac38f9a05/index.js#L21-L25
