### ISSUE TITLE
Waiting for status to be reported

### ISSUE THREAD

**Issue by tomkerkhove** [ahmed-taj/dep#27]
Every now and then the Dep app has the following status:
> Expected — Waiting for status to be reported

Is there a reason for this or is this a bug? This is still the case after a couple of hours and thus blocking PRs.

**Comment by z0al** [comment]
Sorry to hear this :/ 

It's not a bug though. This app is deployed on a free [Now](https://now.sh) instance. Given there are 80+ installations (multiple repos per installation, mostly), I think the [free plan](https://zeit.co/pricing) may not be enough. some of GitHub events might get lost. I believe that case with you.

Fortunately, you can easily deploy your own instance of this app. Check out here for details: [deploy.md](https://github.com/z0al/dep/blob/master/docs/deploy.md).

Please let me know if you need any help!
