### ISSUE TITLE
the DEP step is hanging out... waiting for something that will never happen..

### ISSUE THREAD

**Issue by Raffaello** [ahmed-taj/dep#32]
I think it is crash behind the scene, just not resolving the DEP status check.
please see here:
https://github.com/Raffaello/sdl2-vga-terminal/pull/90

it might be changed again as i am plannig other commits, but it should be resolved or green or red as there is really nothing to wait for.

**Comment by z0al** [comment]
Hey, Thanks for reporting the issue. 

I have a suspicion that it might be related to Now v1 being deprecated (now.sh). I think I got an email but was busy to check it out. I need to check that first in the morning.

**Comment by z0al** [comment]
Actually just by checking the URL it's seems still alive. If you keep getting delayed statuses from time to time then it's probably due the limit of the free tier at https://now.sh . Currently the app has +200 installation (user or GitHub org) so it very likely that the bot misses some GitHub events every now and then.

**Comment by z0al** [comment]
> but it should be resolved or green or red as there is really nothing to wait for.

GitHub is "expecting" a report from the bot (since it's required). It's not that the bot itself reported "waiting...", The bot might not have even received the even (see my message above)

**Comment by z0al** [comment]
I'm going to close this as there is nothing much I can do here. Please feel free to reopen you think makes sense.

**Comment by Raffaello** [comment]
is there any way to diagnose if the event has been lost?

**Comment by Raffaello** [comment]
anyway paying a little bit more attention seems on the "update PR" event that is not working.
if i have some diagnostic tools i might help more...

**Comment by z0al** [comment]
> is there any way to diagnose if the event has been lost?

@Raffaello  I'm not aware of any. As the bot owner, I can see recent events sent to the bot in GitHub UI but it's just an infinite list with no way to filter by status, date ...etc. Since the bot receives more than 10k events a day it's pretty useless.

Sorry couldn't help much here.
