### ISSUE TITLE
Prevent dependency of a PR on itself

### ISSUE THREAD

**Issue by lo1tuma** [ahmed-taj/dep#7]
Currently it is possible to create a PR and mark it to have a dependency on itself.

For example when I create the PR `#5` and then add a comment to this PR `/depends on #5` then dep-bot changes the commit status with the message "Blocked by `#5`".

**Comment by ryanhiebert** [comment]
Is this still applicable after #11 is merged? Since that's a big refactor in progress, it may be best to wait until that's complete for a change on this.

**Comment by z0al** [comment]
Yes, it's applicable. 

> it may be best to wait until that's complete for a change on this.

👍

**Comment by rsarky** [comment]
I have fixed this in #16
