### ISSUE TITLE
Allow commands also within PR description

### ISSUE THREAD

**Issue by lo1tuma** [ahmed-taj/dep#8]
Currently the bot only recognizes the `/depends` command in a PR comment. It would be nice if the bot would also recognize the command within the PR description.

**Comment by z0al** [comment]
Thank you for opening this @lo1tuma, excellent :sparkles: 

Your suggestion definitely makes sense. Actually, I'm thinking (as per @ryanhiebert's [suggestion](https://github.com/ahmed-taj/dep/pull/6#issuecomment-354548370)) to **only** recognize commands in the original PR description. That would also help to avoid #9 and #10 and other technical concerns

If you have any thoughts you would like share please go a head

**Comment by lo1tuma** [comment]
I’m not sure if it would prevent #9 and #10. The PR description can also be edited, which means I could change the `/depends` command or even remove it from the description. It would be also possible to write multiple `/depends` commands in a single description or comment.

But allowing the command only in the PR description would solve at least another problem: which is that people who don’t have push/admin access to the repository couldn’t block any PR just by writing a comment.

**Comment by z0al** [comment]
>  The PR description can also be edited, which means I could change the /depends command or even remove it from the description

Agree. What I meant is that tracking edits (update or remove) of comments is tricky. By allowing commands to be only in the description you can always get the latest/correct dependencies list by matching it against `/<command-regex>/g`. 

> people who don’t have push/admin access to the repository couldn’t block any PR just by writing a comment.

The bot currently checks for push/admin access of the commenter before taking actions. 
https://github.com/ahmed-taj/dep/blob/da4aed8db829e4d3c98db282ff27c0d09eb7c40c/lib/ensure.js#L16-L25

**Comment by lo1tuma** [comment]
True. It would definitely reduce complexity 👍 .



> The bot currently checks for push/admin access of the commenter before taking actions.

Oh, nice... I wasn’t aware of that.
