### ISSUE TITLE
Status is not updated when command is edited or removed

### ISSUE THREAD

**Issue by lo1tuma** [ahmed-taj/dep#9]
The dependency status of a PR is not updated when the comment with the original command is edited or deleted.

For example, when I write the command `/depends on #123` then the status is updated to "blocked by `#123`". When I realize that I’ve made a typo and I edit the comment so it says `/depends on #124` then the status is not updated to "blocked by `#124`".

The same is true for deleting the comment with the command. I would expect the dependency to be removed.

**Comment by z0al** [comment]
Closing this as it's no longer valid due to #11 

Thanks!
